### ISSUE TITLE
Repo is empty

### ISSUE THREAD

**Issue by Victorthemachine** [vavrav03/Sudoku#1]
Hello dear vavrav03,
Your repository is empty and I cannot copy your work. Please fix asap!

**Comment by havrak** [comment]
I would also like you to fix this pressing issue

**Comment by vavrav03** [comment]
It's not an issue, it's by design

**Comment by Victorthemachine** [comment]
Then you leave me no choice but to report for child abuse

**Comment by Victorthemachine** [comment]
pog
