### ISSUE TITLE
Repo is still empty

### ISSUE THREAD

**Issue by Victorthemachine** [vavrav03/Sudoku#2]
You were the shadow to my light
Did you feel us
Another start
You fade away
Afraid our aim is out of sight
Wanna see us
Alive
Where are you now
Where are you now
Where are you now
Was it all in my fantasy
Where are you now
Were you only imaginary
Where are you now
Atlantis
Under the sea
Under the sea
Where are you now
Another dream
The monsters running wild inside of me
I'm faded
I'm faded
So lost
I'm faded
These shallow waters, never met
What I needed
I'm letting go
A deeper dive
Eternal silence of the sea
I'm breathing
Alive
Where are you now
Where are you now
Under the bright
But faded lights
You set my heart on fire
Where are you now
Where are you now
Where are you now
Where are you now
Where are you now
Atlantis
Under the sea
Under the sea
Where are you now
Another dream
The monsters running wild inside of me
I'm faded
I'm faded
So lost
I'm faded

**Comment by havrak** [comment]
The time has come to an end
Yeah – this is what nature planned

Being tracked by a starving beast
Looking for its daily feast
A predator on the verge of death
Close to its last breath
Getting close to its last breath

RULES OF NATURE

And they run when the sun comes up
With their lives on the line
(Alive)
For a while
(No choice)
Gotta follow the laws of the wild
(Alive)
With their lives on the line
(No choice)
Out here only the strong survive

What’s done is done
Survived to see another day
The game of life
The hunter and the agile prey
No guarantee
Which of them will succeed
Strong or weak

(yell)

Rules of Nature
Rules of Nature

**Comment by Victorthemachine** [comment]
In der Dunkelheit, ganz umhüllt
Von tiefer Schwärze Tanzt die Apathie
Doch ich werde ihrem Schritt nicht folgen
Mein Blick ist verhüllt und Ich kann mein
Herz nicht sehen
Selbst wenn es zerbricht
Interessiert - es- mich nicht

Ich beweg mich nicht, stehe still
Und warte schweigend
Doch es trägt mich fort
Denn die Risse der Zeit greifen nach mir
Es berührt mich nicht,
Ich will all das, nur vergessen
Ich bin wie ich bin
Und mehr zählt ja auch nicht.


Träum ich einen Traum?
Sehe ich die Wirklichkeit?
Meine Worte helfen nicht,
Denn ich bin noch nicht bereit
Und die Traurigkeit in mir,
Erschöpft mich in dieser Zeit
Lieber würde ich nichts fühl,
Wäre von dem Leid befreit.

Was du sagst versteh ich nicht,
Es verwirrt mich fürchterlich
Mein Herz halte ich versteckt
Und Gefühle unentdeckt
Jag ich meinen Träumen nach
Werde ich bloß wieder schwach
Und so ich reiße alles mit
In die tiefe Dunkelheit

Hält denn jemand so wie ich
Seine Zukunft in der Hand
Gehör' ich in diese Welt
Oder hab ich's nicht verdient
Warum schmerzt mein Herz so sehr?
Um wen trauer ich denn nur?
Ich versteh mich selber nicht
Seh im Spiegel kein Gesicht.


Und ich laufe ohne Ziel,
Ist das alles nur ein Spiel
Werd geblendet von dem Licht
Doch erreichen kann ich's nicht.
Könnte ich 'ne Andere sein
Bleib ich sicher nicht allein
Und dreh ich mich zu dem Schein
Hüllt er mich letztendlich ein

Und die Zeit vergeht, fließt vorbei
Und in dem Lichte tanzt die Apathie
Und ich werde ihrem Schritt nun folgen
Mein Blick ist verhüllt und ich kann
Mein Herz nicht sehen
Selbst wenn es zerbricht
Interessiert - es - mich nicht

Ich beweg mich nicht, stehe still
Und warte schweigend
Doch es trägt mich fort
Denn die Risse der Zeit greifen nach mir
Es berührt mich nicht,
Ich will all das, nur vergessen
Ich bin wie ich bin
Und mehr zählt ja auch nicht.

Träum ich einen Traum?
Sehe ich die Wirklichkeit?
Meine Worte helfen nicht,
Denn ich bin noch nicht bereit.
Und die Traurigkeit in mir,
Erschöpft mich in dieser Zeit
Lieber würde ich nichts fühl'n,
Wäre von dem Leid befreit.

Was du sagst versteh ich nicht,
Es verwirrt mich fürchterlich
Mein Herz halte ich versteckt
Und Gefühle unentdeckt
Jag ich meinen Träumen nach
Werde ich bloß wieder schwach
Und so ich reiß alles mit,
In die tiefe Dunkelheit

Mache ich nur einen Schritt
Mache ich nur einen Schritt
Zerstör ich das was ich lieb
Zerstör ich das was ich lieb

Drück ich meine Trauer aus
Drück ich meine Trauer aus
Wird mein Herz dann wieder rein
Taucht in weisse Farbe ein

Ich weiß gar nichts über dich
Ich weiß gar nichts über mich
Ich versteh mich selber nicht
Meine Welt hat kein Gesicht
Mach ich meine Augen auf
Nimmt das Unheil seinen Lauf
Und nun zerr ich alles mit
In die tiefe Dunkelheit

**Comment by havrak** [comment]
The audacity of this maintainer is beyond believe.

**Comment by Victorthemachine** [comment]
Closed due to inactivity of the repo owner
